[package]
name = "file-de-dup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "file-de-dup"
path = "src/cli.rs"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
num_cpus = "1.0"